flags: {}
arch: x86_64
system-ghc: true
allow-newer: true
packages:
 - '.'
extra-deps:
- MissingH-1.4.3.0
- aeson-1.5.6.0
- base-unicode-symbols-0.2.4.2
- executable-path-0.0.3.1
- lifted-base-0.2.3.12
- utf8-string-1.0.2
- yaml-0.11.5.0
- attoparsec-0.14.1
- base-compat-batteries-0.12.0
- conduit-1.3.4.1
- data-fix-0.3.2
- dlist-1.0
- hashable-1.3.3.0
- hslogger-1.3.1.0
- libyaml-0.1.2
- monad-control-1.0.3.1
- network-3.1.2.2
- network-bsd-2.8.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- primitive-0.7.2.0
- random-1.1
- regex-compat-0.95.2.1
- resourcet-1.2.4.3
- scientific-0.3.7.0
- strict-0.4.0.1
- tagged-0.8.6.1
- th-abstraction-0.4.3.0
- these-1.1.1.1
- time-compat-1.9.6.1
- transformers-base-0.4.6
- unordered-containers-0.2.14.0
- uuid-types-1.0.5
- vector-0.12.3.0
- assoc-1.0.2
- base-compat-0.12.0
- base-orphans-0.8.5
- integer-logarithms-1.0.3.1
- mono-traversable-1.0.15.1
- regex-base-0.94.0.1
- regex-posix-0.96.0.1
- transformers-compat-0.7
- unliftio-core-0.2.0.1
- bifunctors-5.5.11
- split-0.2.3.4
- vector-algorithms-0.8.0.4
- comonad-5.0.8
- distributive-0.6.2.1
- indexed-traversable-0.1.1
resolver: ghc-9
