flags: {}
arch: x86_64
system-ghc: true
allow-newer: true
packages:
 - '.'
extra-deps:
 - regex-posix-0.96.0.1
 - hslogger-1.3.1.0
 - network-bsd-2.8.1.0
 - regex-compat-0.95.2.1
 - base-unicode-symbols-0.2.4.2
 - MissingH-1.4.3.0
 - executable-path-0.0.3.1
resolver: ghc-8
